"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#ffffff)\
[  ](bg:#ffffff fg:#000000)\
[](bg:#000000 fg:#ffffff)\
$directory\
[](fg:#000000 bg:#ffffff)\
$git_branch\
$git_status\
[](fg:#ffffff bg:#000000)\
$nodejs\
[](fg:#000000 bg:#ffffff)\
$time\
[ ](fg:#ffffff)\
\n$character"""

[character]
success_symbol = '➜'

[directory]
style = "fg:#ffffff bg:#000000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "~/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#000000"
format = '[[ $symbol $branch ](fg:#000000 bg:#ffffff)]($style)'

[git_status]
style = "bg:#000000"
format = '[[($all_status$ahead_behind )](fg:#000000 bg:#ffffff)]($style)'

[nodejs]
symbol = ""
style = "bg:#000000"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#000000)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#ffffff"
format = '[[   $time ](fg:#000000 bg:#ffffff)]($style)'
